app:
  port: 8080
  name: spidergo
  dev: true
  debug: true
  domain: localhost
  secure_cookies: true

db:
  dns: your-postgress-dns

redis:
  address: your-redis-address
  password: your-redis-password
  db: 0
  pool_size: 10
  min_idle_conns: 2
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  pool_timeout: 4s
  max_retries: 2

rate_limiter:
  auth:
    limit: 5
    window: 1m
  api_key:
    max_keys_per_user: 3
    daily_limit: 1000

jwt_config:
    access_key: your-screet-key
    refresh_key: your-refresh-screet-key
    access_ttl: 10m
    refresh_ttl: 48h


google_oauth:
    client_id: your-google-cloud-client-id
    client_secret: your-google-app-client-screet
    redirect_url: your-redirect-url
    user_url: your-user-url
  
github_oauth: 
    client_id: your-github-client-id
    client_secret: your-google-app-client-screet
    redirect_url:  your-redirect-url
    user_url:  your-user-url

email: 
    username: your-email-account
    api_key: your-api-key

crawler:
    allowed_domains:
    max_depth: 10
    max_pages: 100
    max_concurrency: 10
    allowed_paths:
    denied_patterns:
     


