// Code generated by MockGen. DO NOT EDIT.
// Source: Domain/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=Domain/interfaces.go -destination=mocks/interfaces_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "web_crawler_scraper/Domain"

	gomock "go.uber.org/mock/gomock"
)

// MockIUserRepo is a mock of IUserRepo interface.
type MockIUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIUserRepoMockRecorder
	isgomock struct{}
}

// MockIUserRepoMockRecorder is the mock recorder for MockIUserRepo.
type MockIUserRepoMockRecorder struct {
	mock *MockIUserRepo
}

// NewMockIUserRepo creates a new mock instance.
func NewMockIUserRepo(ctrl *gomock.Controller) *MockIUserRepo {
	mock := &MockIUserRepo{ctrl: ctrl}
	mock.recorder = &MockIUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIUserRepo) EXPECT() *MockIUserRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIUserRepo) Create(ctx context.Context, user *domain.User) *domain.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(*domain.AppError)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIUserRepoMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIUserRepo)(nil).Create), ctx, user)
}

// CreateVerificationCode mocks base method.
func (m *MockIUserRepo) CreateVerificationCode(ctx context.Context, verification *domain.VerificationCode) *domain.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVerificationCode", ctx, verification)
	ret0, _ := ret[0].(*domain.AppError)
	return ret0
}

// CreateVerificationCode indicates an expected call of CreateVerificationCode.
func (mr *MockIUserRepoMockRecorder) CreateVerificationCode(ctx, verification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVerificationCode", reflect.TypeOf((*MockIUserRepo)(nil).CreateVerificationCode), ctx, verification)
}

// DeleteVerificationCode mocks base method.
func (m *MockIUserRepo) DeleteVerificationCode(ctx context.Context, email string) *domain.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVerificationCode", ctx, email)
	ret0, _ := ret[0].(*domain.AppError)
	return ret0
}

// DeleteVerificationCode indicates an expected call of DeleteVerificationCode.
func (mr *MockIUserRepoMockRecorder) DeleteVerificationCode(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVerificationCode", reflect.TypeOf((*MockIUserRepo)(nil).DeleteVerificationCode), ctx, email)
}

// FindByEmail mocks base method.
func (m *MockIUserRepo) FindByEmail(ctx context.Context, field string) (*domain.User, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", ctx, field)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockIUserRepoMockRecorder) FindByEmail(ctx, field any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockIUserRepo)(nil).FindByEmail), ctx, field)
}

// FindByID mocks base method.
func (m *MockIUserRepo) FindByID(ctx context.Context, field string) (*domain.User, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, field)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIUserRepoMockRecorder) FindByID(ctx, field any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIUserRepo)(nil).FindByID), ctx, field)
}

// FindVerificationCode mocks base method.
func (m *MockIUserRepo) FindVerificationCode(ctx context.Context, email string) (*domain.VerificationCode, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindVerificationCode", ctx, email)
	ret0, _ := ret[0].(*domain.VerificationCode)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// FindVerificationCode indicates an expected call of FindVerificationCode.
func (mr *MockIUserRepoMockRecorder) FindVerificationCode(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindVerificationCode", reflect.TypeOf((*MockIUserRepo)(nil).FindVerificationCode), ctx, email)
}

// SaveProvider mocks base method.
func (m *MockIUserRepo) SaveProvider(ctx context.Context, provider *domain.AuthProvider) *domain.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveProvider", ctx, provider)
	ret0, _ := ret[0].(*domain.AppError)
	return ret0
}

// SaveProvider indicates an expected call of SaveProvider.
func (mr *MockIUserRepoMockRecorder) SaveProvider(ctx, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveProvider", reflect.TypeOf((*MockIUserRepo)(nil).SaveProvider), ctx, provider)
}

// Update mocks base method.
func (m *MockIUserRepo) Update(ctx context.Context, user *domain.User) (*domain.User, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIUserRepoMockRecorder) Update(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIUserRepo)(nil).Update), ctx, user)
}

// MockIRefreshTokenRepo is a mock of IRefreshTokenRepo interface.
type MockIRefreshTokenRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIRefreshTokenRepoMockRecorder
	isgomock struct{}
}

// MockIRefreshTokenRepoMockRecorder is the mock recorder for MockIRefreshTokenRepo.
type MockIRefreshTokenRepoMockRecorder struct {
	mock *MockIRefreshTokenRepo
}

// NewMockIRefreshTokenRepo creates a new mock instance.
func NewMockIRefreshTokenRepo(ctrl *gomock.Controller) *MockIRefreshTokenRepo {
	mock := &MockIRefreshTokenRepo{ctrl: ctrl}
	mock.recorder = &MockIRefreshTokenRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRefreshTokenRepo) EXPECT() *MockIRefreshTokenRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockIRefreshTokenRepo) Create(ctx context.Context, token *domain.RefreshToken) *domain.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(*domain.AppError)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIRefreshTokenRepoMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIRefreshTokenRepo)(nil).Create), ctx, token)
}

// DeleteToken mocks base method.
func (m *MockIRefreshTokenRepo) DeleteToken(ctx context.Context, token string) *domain.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteToken", ctx, token)
	ret0, _ := ret[0].(*domain.AppError)
	return ret0
}

// DeleteToken indicates an expected call of DeleteToken.
func (mr *MockIRefreshTokenRepoMockRecorder) DeleteToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteToken", reflect.TypeOf((*MockIRefreshTokenRepo)(nil).DeleteToken), ctx, token)
}

// FindByID mocks base method.
func (m *MockIRefreshTokenRepo) FindByID(ctx context.Context, UserID string) (*domain.RefreshToken, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, UserID)
	ret0, _ := ret[0].(*domain.RefreshToken)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockIRefreshTokenRepoMockRecorder) FindByID(ctx, UserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockIRefreshTokenRepo)(nil).FindByID), ctx, UserID)
}

// Update mocks base method.
func (m *MockIRefreshTokenRepo) Update(ctx context.Context, token *domain.RefreshToken) *domain.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, token)
	ret0, _ := ret[0].(*domain.AppError)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIRefreshTokenRepoMockRecorder) Update(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIRefreshTokenRepo)(nil).Update), ctx, token)
}

// MockIOAuthServices is a mock of IOAuthServices interface.
type MockIOAuthServices struct {
	ctrl     *gomock.Controller
	recorder *MockIOAuthServicesMockRecorder
	isgomock struct{}
}

// MockIOAuthServicesMockRecorder is the mock recorder for MockIOAuthServices.
type MockIOAuthServicesMockRecorder struct {
	mock *MockIOAuthServices
}

// NewMockIOAuthServices creates a new mock instance.
func NewMockIOAuthServices(ctrl *gomock.Controller) *MockIOAuthServices {
	mock := &MockIOAuthServices{ctrl: ctrl}
	mock.recorder = &MockIOAuthServicesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOAuthServices) EXPECT() *MockIOAuthServicesMockRecorder {
	return m.recorder
}

// Exchange mocks base method.
func (m *MockIOAuthServices) Exchange(arg0 context.Context, arg1, arg2 string) (*domain.ExchangeData, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exchange", arg0, arg1, arg2)
	ret0, _ := ret[0].(*domain.ExchangeData)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// Exchange indicates an expected call of Exchange.
func (mr *MockIOAuthServicesMockRecorder) Exchange(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exchange", reflect.TypeOf((*MockIOAuthServices)(nil).Exchange), arg0, arg1, arg2)
}

// GetAuthURL mocks base method.
func (m *MockIOAuthServices) GetAuthURL(providerName, state string) (string, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthURL", providerName, state)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// GetAuthURL indicates an expected call of GetAuthURL.
func (mr *MockIOAuthServicesMockRecorder) GetAuthURL(providerName, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthURL", reflect.TypeOf((*MockIOAuthServices)(nil).GetAuthURL), providerName, state)
}

// RefreshToken mocks base method.
func (m *MockIOAuthServices) RefreshToken(ctx context.Context, token *domain.RefreshToken) (*domain.RefreshToken, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, token)
	ret0, _ := ret[0].(*domain.RefreshToken)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockIOAuthServicesMockRecorder) RefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockIOAuthServices)(nil).RefreshToken), ctx, token)
}

// MockIJwtService is a mock of IJwtService interface.
type MockIJwtService struct {
	ctrl     *gomock.Controller
	recorder *MockIJwtServiceMockRecorder
	isgomock struct{}
}

// MockIJwtServiceMockRecorder is the mock recorder for MockIJwtService.
type MockIJwtServiceMockRecorder struct {
	mock *MockIJwtService
}

// NewMockIJwtService creates a new mock instance.
func NewMockIJwtService(ctrl *gomock.Controller) *MockIJwtService {
	mock := &MockIJwtService{ctrl: ctrl}
	mock.recorder = &MockIJwtServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIJwtService) EXPECT() *MockIJwtServiceMockRecorder {
	return m.recorder
}

// GenerateTokens mocks base method.
func (m *MockIJwtService) GenerateTokens(ctx context.Context, userID string) (*domain.ExchangeData, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokens", ctx, userID)
	ret0, _ := ret[0].(*domain.ExchangeData)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// GenerateTokens indicates an expected call of GenerateTokens.
func (mr *MockIJwtServiceMockRecorder) GenerateTokens(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokens", reflect.TypeOf((*MockIJwtService)(nil).GenerateTokens), ctx, userID)
}

// RefreshToken mocks base method.
func (m *MockIJwtService) RefreshToken(ctx context.Context, refreshToken string) (*domain.ExchangeData, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(*domain.ExchangeData)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockIJwtServiceMockRecorder) RefreshToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockIJwtService)(nil).RefreshToken), ctx, refreshToken)
}

// ValidateToken mocks base method.
func (m *MockIJwtService) ValidateToken(tokenString, tokenName string) (*domain.Claims, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", tokenString, tokenName)
	ret0, _ := ret[0].(*domain.Claims)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockIJwtServiceMockRecorder) ValidateToken(tokenString, tokenName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockIJwtService)(nil).ValidateToken), tokenString, tokenName)
}

// MockIPasswordService is a mock of IPasswordService interface.
type MockIPasswordService struct {
	ctrl     *gomock.Controller
	recorder *MockIPasswordServiceMockRecorder
	isgomock struct{}
}

// MockIPasswordServiceMockRecorder is the mock recorder for MockIPasswordService.
type MockIPasswordServiceMockRecorder struct {
	mock *MockIPasswordService
}

// NewMockIPasswordService creates a new mock instance.
func NewMockIPasswordService(ctrl *gomock.Controller) *MockIPasswordService {
	mock := &MockIPasswordService{ctrl: ctrl}
	mock.recorder = &MockIPasswordServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPasswordService) EXPECT() *MockIPasswordServiceMockRecorder {
	return m.recorder
}

// ComparePassword mocks base method.
func (m *MockIPasswordService) ComparePassword(hashedPassword, password string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComparePassword", hashedPassword, password)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ComparePassword indicates an expected call of ComparePassword.
func (mr *MockIPasswordServiceMockRecorder) ComparePassword(hashedPassword, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComparePassword", reflect.TypeOf((*MockIPasswordService)(nil).ComparePassword), hashedPassword, password)
}

// HashPassword mocks base method.
func (m *MockIPasswordService) HashPassword(password string) (string, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashPassword", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// HashPassword indicates an expected call of HashPassword.
func (mr *MockIPasswordServiceMockRecorder) HashPassword(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashPassword", reflect.TypeOf((*MockIPasswordService)(nil).HashPassword), password)
}

// MockIEmailService is a mock of IEmailService interface.
type MockIEmailService struct {
	ctrl     *gomock.Controller
	recorder *MockIEmailServiceMockRecorder
	isgomock struct{}
}

// MockIEmailServiceMockRecorder is the mock recorder for MockIEmailService.
type MockIEmailServiceMockRecorder struct {
	mock *MockIEmailService
}

// NewMockIEmailService creates a new mock instance.
func NewMockIEmailService(ctrl *gomock.Controller) *MockIEmailService {
	mock := &MockIEmailService{ctrl: ctrl}
	mock.recorder = &MockIEmailServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIEmailService) EXPECT() *MockIEmailServiceMockRecorder {
	return m.recorder
}

// SendEmail mocks base method.
func (m *MockIEmailService) SendEmail(name, subject, otp string, to []string) *domain.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendEmail", name, subject, otp, to)
	ret0, _ := ret[0].(*domain.AppError)
	return ret0
}

// SendEmail indicates an expected call of SendEmail.
func (mr *MockIEmailServiceMockRecorder) SendEmail(name, subject, otp, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendEmail", reflect.TypeOf((*MockIEmailService)(nil).SendEmail), name, subject, otp, to)
}

// MockIResultRepo is a mock of IResultRepo interface.
type MockIResultRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIResultRepoMockRecorder
	isgomock struct{}
}

// MockIResultRepoMockRecorder is the mock recorder for MockIResultRepo.
type MockIResultRepoMockRecorder struct {
	mock *MockIResultRepo
}

// NewMockIResultRepo creates a new mock instance.
func NewMockIResultRepo(ctrl *gomock.Controller) *MockIResultRepo {
	mock := &MockIResultRepo{ctrl: ctrl}
	mock.recorder = &MockIResultRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIResultRepo) EXPECT() *MockIResultRepoMockRecorder {
	return m.recorder
}

// FindAllHistory mocks base method.
func (m *MockIResultRepo) FindAllHistory(ctx context.Context, userID string) ([]domain.History, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllHistory", ctx, userID)
	ret0, _ := ret[0].([]domain.History)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// FindAllHistory indicates an expected call of FindAllHistory.
func (mr *MockIResultRepoMockRecorder) FindAllHistory(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllHistory", reflect.TypeOf((*MockIResultRepo)(nil).FindAllHistory), ctx, userID)
}

// SaveHistory mocks base method.
func (m *MockIResultRepo) SaveHistory(ctx context.Context, history *domain.History) *domain.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveHistory", ctx, history)
	ret0, _ := ret[0].(*domain.AppError)
	return ret0
}

// SaveHistory indicates an expected call of SaveHistory.
func (mr *MockIResultRepoMockRecorder) SaveHistory(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveHistory", reflect.TypeOf((*MockIResultRepo)(nil).SaveHistory), ctx, history)
}

// SaveResult mocks base method.
func (m *MockIResultRepo) SaveResult(ctx context.Context, result *domain.CrawlerResult) *domain.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveResult", ctx, result)
	ret0, _ := ret[0].(*domain.AppError)
	return ret0
}

// SaveResult indicates an expected call of SaveResult.
func (mr *MockIResultRepoMockRecorder) SaveResult(ctx, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveResult", reflect.TypeOf((*MockIResultRepo)(nil).SaveResult), ctx, result)
}

// MockIApiKeyRepo is a mock of IApiKeyRepo interface.
type MockIApiKeyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIApiKeyRepoMockRecorder
	isgomock struct{}
}

// MockIApiKeyRepoMockRecorder is the mock recorder for MockIApiKeyRepo.
type MockIApiKeyRepoMockRecorder struct {
	mock *MockIApiKeyRepo
}

// NewMockIApiKeyRepo creates a new mock instance.
func NewMockIApiKeyRepo(ctrl *gomock.Controller) *MockIApiKeyRepo {
	mock := &MockIApiKeyRepo{ctrl: ctrl}
	mock.recorder = &MockIApiKeyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIApiKeyRepo) EXPECT() *MockIApiKeyRepoMockRecorder {
	return m.recorder
}

// CountActiveByUserID mocks base method.
func (m *MockIApiKeyRepo) CountActiveByUserID(ctx context.Context, userID string) (int64, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveByUserID", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// CountActiveByUserID indicates an expected call of CountActiveByUserID.
func (mr *MockIApiKeyRepoMockRecorder) CountActiveByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveByUserID", reflect.TypeOf((*MockIApiKeyRepo)(nil).CountActiveByUserID), ctx, userID)
}

// Create mocks base method.
func (m *MockIApiKeyRepo) Create(ctx context.Context, key *domain.ApiKey) *domain.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, key)
	ret0, _ := ret[0].(*domain.AppError)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIApiKeyRepoMockRecorder) Create(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIApiKeyRepo)(nil).Create), ctx, key)
}

// FindAllByUserID mocks base method.
func (m *MockIApiKeyRepo) FindAllByUserID(ctx context.Context, userID string) ([]domain.ApiKey, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByUserID", ctx, userID)
	ret0, _ := ret[0].([]domain.ApiKey)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// FindAllByUserID indicates an expected call of FindAllByUserID.
func (mr *MockIApiKeyRepoMockRecorder) FindAllByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByUserID", reflect.TypeOf((*MockIApiKeyRepo)(nil).FindAllByUserID), ctx, userID)
}

// FindByHash mocks base method.
func (m *MockIApiKeyRepo) FindByHash(ctx context.Context, hash string) (*domain.ApiKey, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHash", ctx, hash)
	ret0, _ := ret[0].(*domain.ApiKey)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// FindByHash indicates an expected call of FindByHash.
func (mr *MockIApiKeyRepoMockRecorder) FindByHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHash", reflect.TypeOf((*MockIApiKeyRepo)(nil).FindByHash), ctx, hash)
}

// FindByIDAndUserID mocks base method.
func (m *MockIApiKeyRepo) FindByIDAndUserID(ctx context.Context, keyID, userID string) (*domain.ApiKey, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDAndUserID", ctx, keyID, userID)
	ret0, _ := ret[0].(*domain.ApiKey)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// FindByIDAndUserID indicates an expected call of FindByIDAndUserID.
func (mr *MockIApiKeyRepoMockRecorder) FindByIDAndUserID(ctx, keyID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDAndUserID", reflect.TypeOf((*MockIApiKeyRepo)(nil).FindByIDAndUserID), ctx, keyID, userID)
}

// Revoke mocks base method.
func (m *MockIApiKeyRepo) Revoke(ctx context.Context, keyID, userID string) *domain.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, keyID, userID)
	ret0, _ := ret[0].(*domain.AppError)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockIApiKeyRepoMockRecorder) Revoke(ctx, keyID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockIApiKeyRepo)(nil).Revoke), ctx, keyID, userID)
}

// TouchLastUsed mocks base method.
func (m *MockIApiKeyRepo) TouchLastUsed(ctx context.Context, keyID string) *domain.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchLastUsed", ctx, keyID)
	ret0, _ := ret[0].(*domain.AppError)
	return ret0
}

// TouchLastUsed indicates an expected call of TouchLastUsed.
func (mr *MockIApiKeyRepoMockRecorder) TouchLastUsed(ctx, keyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchLastUsed", reflect.TypeOf((*MockIApiKeyRepo)(nil).TouchLastUsed), ctx, keyID)
}

// MockIApiKeyAuthService is a mock of IApiKeyAuthService interface.
type MockIApiKeyAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockIApiKeyAuthServiceMockRecorder
	isgomock struct{}
}

// MockIApiKeyAuthServiceMockRecorder is the mock recorder for MockIApiKeyAuthService.
type MockIApiKeyAuthServiceMockRecorder struct {
	mock *MockIApiKeyAuthService
}

// NewMockIApiKeyAuthService creates a new mock instance.
func NewMockIApiKeyAuthService(ctrl *gomock.Controller) *MockIApiKeyAuthService {
	mock := &MockIApiKeyAuthService{ctrl: ctrl}
	mock.recorder = &MockIApiKeyAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIApiKeyAuthService) EXPECT() *MockIApiKeyAuthServiceMockRecorder {
	return m.recorder
}

// TouchLastUsed mocks base method.
func (m *MockIApiKeyAuthService) TouchLastUsed(ctx context.Context, keyID string) *domain.AppError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchLastUsed", ctx, keyID)
	ret0, _ := ret[0].(*domain.AppError)
	return ret0
}

// TouchLastUsed indicates an expected call of TouchLastUsed.
func (mr *MockIApiKeyAuthServiceMockRecorder) TouchLastUsed(ctx, keyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchLastUsed", reflect.TypeOf((*MockIApiKeyAuthService)(nil).TouchLastUsed), ctx, keyID)
}

// ValidateAPIKey mocks base method.
func (m *MockIApiKeyAuthService) ValidateAPIKey(ctx context.Context, rawKey string) (*domain.ApiKey, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAPIKey", ctx, rawKey)
	ret0, _ := ret[0].(*domain.ApiKey)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// ValidateAPIKey indicates an expected call of ValidateAPIKey.
func (mr *MockIApiKeyAuthServiceMockRecorder) ValidateAPIKey(ctx, rawKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAPIKey", reflect.TypeOf((*MockIApiKeyAuthService)(nil).ValidateAPIKey), ctx, rawKey)
}

// MockIApiKeyRateLimiter is a mock of IApiKeyRateLimiter interface.
type MockIApiKeyRateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockIApiKeyRateLimiterMockRecorder
	isgomock struct{}
}

// MockIApiKeyRateLimiterMockRecorder is the mock recorder for MockIApiKeyRateLimiter.
type MockIApiKeyRateLimiterMockRecorder struct {
	mock *MockIApiKeyRateLimiter
}

// NewMockIApiKeyRateLimiter creates a new mock instance.
func NewMockIApiKeyRateLimiter(ctrl *gomock.Controller) *MockIApiKeyRateLimiter {
	mock := &MockIApiKeyRateLimiter{ctrl: ctrl}
	mock.recorder = &MockIApiKeyRateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIApiKeyRateLimiter) EXPECT() *MockIApiKeyRateLimiterMockRecorder {
	return m.recorder
}

// AllowByKey mocks base method.
func (m *MockIApiKeyRateLimiter) AllowByKey(ctx context.Context, keyID string, limit int64) (bool, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllowByKey", ctx, keyID, limit)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// AllowByKey indicates an expected call of AllowByKey.
func (mr *MockIApiKeyRateLimiterMockRecorder) AllowByKey(ctx, keyID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllowByKey", reflect.TypeOf((*MockIApiKeyRateLimiter)(nil).AllowByKey), ctx, keyID, limit)
}

// MockICrawlerService is a mock of ICrawlerService interface.
type MockICrawlerService struct {
	ctrl     *gomock.Controller
	recorder *MockICrawlerServiceMockRecorder
	isgomock struct{}
}

// MockICrawlerServiceMockRecorder is the mock recorder for MockICrawlerService.
type MockICrawlerServiceMockRecorder struct {
	mock *MockICrawlerService
}

// NewMockICrawlerService creates a new mock instance.
func NewMockICrawlerService(ctrl *gomock.Controller) *MockICrawlerService {
	mock := &MockICrawlerService{ctrl: ctrl}
	mock.recorder = &MockICrawlerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICrawlerService) EXPECT() *MockICrawlerServiceMockRecorder {
	return m.recorder
}

// Crawl mocks base method.
func (m *MockICrawlerService) Crawl(ctx context.Context, seedURL string) (*domain.CrawlerResult, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Crawl", ctx, seedURL)
	ret0, _ := ret[0].(*domain.CrawlerResult)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// Crawl indicates an expected call of Crawl.
func (mr *MockICrawlerServiceMockRecorder) Crawl(ctx, seedURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Crawl", reflect.TypeOf((*MockICrawlerService)(nil).Crawl), ctx, seedURL)
}

// MockIScrapeService is a mock of IScrapeService interface.
type MockIScrapeService struct {
	ctrl     *gomock.Controller
	recorder *MockIScrapeServiceMockRecorder
	isgomock struct{}
}

// MockIScrapeServiceMockRecorder is the mock recorder for MockIScrapeService.
type MockIScrapeServiceMockRecorder struct {
	mock *MockIScrapeService
}

// NewMockIScrapeService creates a new mock instance.
func NewMockIScrapeService(ctrl *gomock.Controller) *MockIScrapeService {
	mock := &MockIScrapeService{ctrl: ctrl}
	mock.recorder = &MockIScrapeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIScrapeService) EXPECT() *MockIScrapeServiceMockRecorder {
	return m.recorder
}

// FetchAndParse mocks base method.
func (m *MockIScrapeService) FetchAndParse(targetURL, resultID, userID string) (*domain.Page, []string, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAndParse", targetURL, resultID, userID)
	ret0, _ := ret[0].(*domain.Page)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(*domain.AppError)
	return ret0, ret1, ret2
}

// FetchAndParse indicates an expected call of FetchAndParse.
func (mr *MockIScrapeServiceMockRecorder) FetchAndParse(targetURL, resultID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAndParse", reflect.TypeOf((*MockIScrapeService)(nil).FetchAndParse), targetURL, resultID, userID)
}

// MockICrawlerServiceFactory is a mock of ICrawlerServiceFactory interface.
type MockICrawlerServiceFactory struct {
	ctrl     *gomock.Controller
	recorder *MockICrawlerServiceFactoryMockRecorder
	isgomock struct{}
}

// MockICrawlerServiceFactoryMockRecorder is the mock recorder for MockICrawlerServiceFactory.
type MockICrawlerServiceFactoryMockRecorder struct {
	mock *MockICrawlerServiceFactory
}

// NewMockICrawlerServiceFactory creates a new mock instance.
func NewMockICrawlerServiceFactory(ctrl *gomock.Controller) *MockICrawlerServiceFactory {
	mock := &MockICrawlerServiceFactory{ctrl: ctrl}
	mock.recorder = &MockICrawlerServiceFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICrawlerServiceFactory) EXPECT() *MockICrawlerServiceFactoryMockRecorder {
	return m.recorder
}

// NewCrawlerService mocks base method.
func (m *MockICrawlerServiceFactory) NewCrawlerService(userID string) domain.ICrawlerService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewCrawlerService", userID)
	ret0, _ := ret[0].(domain.ICrawlerService)
	return ret0
}

// NewCrawlerService indicates an expected call of NewCrawlerService.
func (mr *MockICrawlerServiceFactoryMockRecorder) NewCrawlerService(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewCrawlerService", reflect.TypeOf((*MockICrawlerServiceFactory)(nil).NewCrawlerService), userID)
}

// MockIScraperServiceFactory is a mock of IScraperServiceFactory interface.
type MockIScraperServiceFactory struct {
	ctrl     *gomock.Controller
	recorder *MockIScraperServiceFactoryMockRecorder
	isgomock struct{}
}

// MockIScraperServiceFactoryMockRecorder is the mock recorder for MockIScraperServiceFactory.
type MockIScraperServiceFactoryMockRecorder struct {
	mock *MockIScraperServiceFactory
}

// NewMockIScraperServiceFactory creates a new mock instance.
func NewMockIScraperServiceFactory(ctrl *gomock.Controller) *MockIScraperServiceFactory {
	mock := &MockIScraperServiceFactory{ctrl: ctrl}
	mock.recorder = &MockIScraperServiceFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIScraperServiceFactory) EXPECT() *MockIScraperServiceFactoryMockRecorder {
	return m.recorder
}

// NewScraperService mocks base method.
func (m *MockIScraperServiceFactory) NewScraperService() domain.IScrapeService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewScraperService")
	ret0, _ := ret[0].(domain.IScrapeService)
	return ret0
}

// NewScraperService indicates an expected call of NewScraperService.
func (mr *MockIScraperServiceFactoryMockRecorder) NewScraperService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewScraperService", reflect.TypeOf((*MockIScraperServiceFactory)(nil).NewScraperService))
}

// MockIRateLimiter is a mock of IRateLimiter interface.
type MockIRateLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockIRateLimiterMockRecorder
	isgomock struct{}
}

// MockIRateLimiterMockRecorder is the mock recorder for MockIRateLimiter.
type MockIRateLimiterMockRecorder struct {
	mock *MockIRateLimiter
}

// NewMockIRateLimiter creates a new mock instance.
func NewMockIRateLimiter(ctrl *gomock.Controller) *MockIRateLimiter {
	mock := &MockIRateLimiter{ctrl: ctrl}
	mock.recorder = &MockIRateLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRateLimiter) EXPECT() *MockIRateLimiterMockRecorder {
	return m.recorder
}

// Allow mocks base method.
func (m *MockIRateLimiter) Allow(ctx context.Context, ip string) (bool, *domain.AppError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Allow", ctx, ip)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(*domain.AppError)
	return ret0, ret1
}

// Allow indicates an expected call of Allow.
func (mr *MockIRateLimiterMockRecorder) Allow(ctx, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Allow", reflect.TypeOf((*MockIRateLimiter)(nil).Allow), ctx, ip)
}
