// Auto-generated by @farming-labs/next — do not edit manually.

import { getMDXComponents } from "@farming-labs/theme/mdx";
import type { MDXComponents } from "mdx/types";
import docsConfig from "@/docs.config";

export function useMDXComponents(components?: MDXComponents): MDXComponents {
  return getMDXComponents(
    {
      ...(docsConfig.components as MDXComponents),
      ...components,
    },
    {
      onCopyClick: docsConfig.onCopyClick,
      theme: docsConfig.theme,
    },
  );
}
