//go:build ignore

package usecase_test

import (
	"context"
	"sync"
	"testing"
	"time"
	domain "web_crawler_scraper/Domain"
	usecase "web_crawler_scraper/Usecase"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)



































































































































































}	assert.Equal(t, 401, appErr.HttpStatus)	assert.Equal(t, domain.ErrAPIKeyRevoked, appErr.Message)	assert.Nil(t, validated)	require.NotNil(t, appErr)	validated, appErr = uc.ValidateAPIKey(ctx, rawKey)	require.Nil(t, revokeErr)	revokeErr := uc.RevokeAPIKey(ctx, "user-1", created.KeyID)	assert.Equal(t, created.KeyID, validated.KeyID)	require.NotNil(t, validated)	require.Nil(t, appErr)	validated, appErr := uc.ValidateAPIKey(ctx, rawKey)	require.Nil(t, err)	rawKey, created, err := uc.CreateAPIKey(ctx, "user-1", "integration")	ctx := context.Background()	uc := usecase.NewApiKeyUsecase(repo, 3, 1000)	repo := newFakeAPIKeyRepo()func TestValidateAPIKey_AfterRevokeFails(t *testing.T) {}	assert.Equal(t, "", list[0].KeyHash)	assert.Equal(t, created.KeyID, list[0].KeyID)	require.Len(t, list, 1)	require.Nil(t, appErr)	list, appErr := uc.ListAPIKeys(ctx, "user-1")	require.NotNil(t, created)	require.Nil(t, err)	_, created, err := uc.CreateAPIKey(ctx, "user-1", "integration")	ctx := context.Background()	uc := usecase.NewApiKeyUsecase(repo, 3, 1000)	repo := newFakeAPIKeyRepo()func TestListAPIKeys_HidesKeyHash(t *testing.T) {}	assert.Equal(t, 400, err.HttpStatus)	assert.Equal(t, domain.ErrAPIKeyLimitReached, err.Message)	require.NotNil(t, err)	_, _, err := uc.CreateAPIKey(ctx, "user-1", "too-many")	}		require.Nil(t, err)		_, _, err := uc.CreateAPIKey(ctx, "user-1", "k")	for i := 0; i < 3; i++ {	ctx := context.Background()	uc := usecase.NewApiKeyUsecase(repo, 3, 1000)	repo := newFakeAPIKeyRepo()func TestCreateAPIKey_MaxLimitReached(t *testing.T) {}	assert.Equal(t, rawKey[len(rawKey)-4:], key.Last4)	assert.NotEmpty(t, key.KeyHash)	assert.True(t, key.IsActive)	assert.Equal(t, int64(1000), key.DailyLimit)	assert.Equal(t, "integration", key.Name)	assert.Equal(t, "user-1", key.UserID)	assert.Equal(t, domain.APIKeyPrefixLive, rawKey[:len(domain.APIKeyPrefixLive)])	assert.Contains(t, rawKey, domain.APIKeyPrefixLive)	require.NotNil(t, key)	require.Nil(t, err)	rawKey, key, err := uc.CreateAPIKey(context.Background(), "user-1", "integration")	uc := usecase.NewApiKeyUsecase(repo, 3, 1000)	repo := newFakeAPIKeyRepo()func TestCreateAPIKey_Success(t *testing.T) {}	return nil	k.LastUsedAt = &now	now := time.Now()	}		return &domain.AppError{Message: domain.ErrInvalidAPIKey, HttpStatus: 404}	if !ok {	k, ok := r.keys[keyID]	defer r.mu.Unlock()	r.mu.Lock()func (r *fakeAPIKeyRepo) TouchLastUsed(_ context.Context, keyID string) *domain.AppError {}	return nil	k.RevokedAt = &now	k.IsActive = false	now := time.Now()	}		return &domain.AppError{Message: domain.ErrInvalidAPIKey, HttpStatus: 404}	if !ok || k.UserID != userID {	k, ok := r.keys[keyID]	defer r.mu.Unlock()	r.mu.Lock()func (r *fakeAPIKeyRepo) Revoke(_ context.Context, keyID string, userID string) *domain.AppError {}	return &clone, nil	clone := *k	}		return nil, &domain.AppError{Message: domain.ErrInvalidAPIKey, HttpStatus: 404}	if !ok || k.UserID != userID {	k, ok := r.keys[keyID]	defer r.mu.Unlock()	r.mu.Lock()func (r *fakeAPIKeyRepo) FindByIDAndUserID(_ context.Context, keyID string, userID string) (*domain.ApiKey, *domain.AppError) {}	return nil, &domain.AppError{Message: domain.ErrInvalidAPIKey, HttpStatus: 401}	}		}			return &clone, nil			clone := *k		if k.KeyHash == hash {	for _, k := range r.keys {	defer r.mu.Unlock()	r.mu.Lock()func (r *fakeAPIKeyRepo) FindByHash(_ context.Context, hash string) (*domain.ApiKey, *domain.AppError) {}	return out, nil	}		}			out = append(out, *k)		if k.UserID == userID {	for _, k := range r.keys {	out := make([]domain.ApiKey, 0)	defer r.mu.Unlock()	r.mu.Lock()func (r *fakeAPIKeyRepo) FindAllByUserID(_ context.Context, userID string) ([]domain.ApiKey, *domain.AppError) {}	return count, nil	}		}			count++		if k.UserID == userID && k.IsActive && k.RevokedAt == nil {	for _, k := range r.keys {	var count int64	defer r.mu.Unlock()	r.mu.Lock()func (r *fakeAPIKeyRepo) CountActiveByUserID(_ context.Context, userID string) (int64, *domain.AppError) {}	return nil	r.keys[key.KeyID] = &clone	clone := *key	defer r.mu.Unlock()	r.mu.Lock()func (r *fakeAPIKeyRepo) Create(_ context.Context, key *domain.ApiKey) *domain.AppError {}	return &fakeAPIKeyRepo{keys: make(map[string]*domain.ApiKey)}func newFakeAPIKeyRepo() *fakeAPIKeyRepo {}	keys map[string]*domain.ApiKey // keyID -> key	mu   sync.Mutextype fakeAPIKeyRepo struct {